// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stocks.Entities;

namespace Stocks.Entities.Migrations
{
    [DbContext(typeof(StocksContext))]
    partial class StocksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Stocks.Entities.Authorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpiresIn")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RefreshTokenExpiresIn")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authorization");
                });

            modelBuilder.Entity("Stocks.Entities.CurrentBalance", b =>
                {
                    b.Property<string>("SecuritiesAccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("AccruedInterest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BondValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashAvailableForTrading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashAvailableForWithdrawal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashCall")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashDebitCallValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CashReceipts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LiquidationValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LongMarketValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LongNonMarginableMarketValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LongOptionMarketValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MoneyMarketFund")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PendingDeposits")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Savings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShortMarketValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShortOptionMarketValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnsettledCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("SecuritiesAccountId");

                    b.ToTable("CurrentBalance");
                });

            modelBuilder.Entity("Stocks.Entities.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cusip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PositionId")
                        .IsUnique();

                    b.ToTable("Instrument");
                });

            modelBuilder.Entity("Stocks.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentDayProfitLoss")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("CurrentDayProfitLossPercentage")
                        .HasColumnType("float");

                    b.Property<double>("LongQuantity")
                        .HasColumnType("float");

                    b.Property<double>("MarketValue")
                        .HasColumnType("float");

                    b.Property<string>("SecuritiesAccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("SettledLongQuantity")
                        .HasColumnType("float");

                    b.Property<double>("SettledShortQuantity")
                        .HasColumnType("float");

                    b.Property<double>("ShortQuantity")
                        .HasColumnType("float");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SecuritiesAccountId");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("Stocks.Entities.PriceHistory", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Symbol", "DateTime");

                    b.HasAlternateKey("Id");

                    b.ToTable("PriceHistory");
                });

            modelBuilder.Entity("Stocks.Entities.SecuritiesAccount", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsClosingOnlyRestricted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDayTrader")
                        .HasColumnType("bit");

                    b.Property<int>("RoundTrips")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountId");

                    b.ToTable("SecuritiesAccount");
                });

            modelBuilder.Entity("Stocks.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("Stocks.Entities.Ticker", b =>
                {
                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpoYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastSale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummaryQuote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Symbol");

                    b.ToTable("Ticker");
                });

            modelBuilder.Entity("Stocks.Entities.CurrentBalance", b =>
                {
                    b.HasOne("Stocks.Entities.SecuritiesAccount", "SecuritiesAccountIdNavigation")
                        .WithOne("CurrentBalances")
                        .HasForeignKey("Stocks.Entities.CurrentBalance", "SecuritiesAccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Stocks.Entities.Instrument", b =>
                {
                    b.HasOne("Stocks.Entities.Position", "PositionIdNavigation")
                        .WithOne("Instrument")
                        .HasForeignKey("Stocks.Entities.Instrument", "PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stocks.Entities.Position", b =>
                {
                    b.HasOne("Stocks.Entities.SecuritiesAccount", "SecuritiesAccountIdNavigation")
                        .WithMany("Positions")
                        .HasForeignKey("SecuritiesAccountId");
                });

            modelBuilder.Entity("Stocks.Entities.PriceHistory", b =>
                {
                    b.HasOne("Stocks.Entities.Ticker", "SymbolNavigation")
                        .WithMany("PriceHistory")
                        .HasForeignKey("Symbol")
                        .HasConstraintName("FK_PriceHistory_Ticker")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
